services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: ragspert_pgvector
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./postgres_cmd/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - internal
    security_opt:
      - no-new-privileges:true

  ragspert:
    image: qoder1337/apitabnew:ragspertv0.1
    container_name: ragspert_app
    environment:
      APP_ENV: ${APP_ENV}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PGVECTOR_EMBED_STORE: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgvector:5432/${POSTGRES_DB}
    restart: unless-stopped
    shm_size: '2gb'
    depends_on:
      - pgvector
    security_opt:
      - no-new-privileges:true
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy
      traefik.http.routers.ragspert-secure.entrypoints: websecure
      traefik.http.routers.ragspert-secure.rule: Host(`ragspert.de`)
      traefik.http.routers.ragspert-secure.tls: "true"
      traefik.http.routers.ragspert-secure.tls.certresolver: http_resolver
      traefik.http.routers.ragspert-secure.middlewares: default@file
      traefik.http.routers.ragspert-secure.service: ragspert
      traefik.http.routers.ragspert.entrypoints: web
      traefik.http.routers.ragspert.rule: Host(`ragspert.de`)
      traefik.http.services.ragspert.loadbalancer.server.port: "8080"
    networks:
      - internal
      - proxy

volumes:
  pgvector_data:
    driver: local

networks:
  internal:
    driver: bridge
    internal: true
  proxy:
    external: true
