services:
  pgvector:
    image: qoder1337/apitabnew:ragspert-pgvectorv0.1
    container_name: ragspert_pgvector
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - internal
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ragspert:
    image: qoder1337/apitabnew:ragspertv0.30
    container_name: ragspert_app
    environment:
      APP_ENV: ${APP_ENV}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/gcloud-ragspert.json
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      PGVECTOR_EMBED_STORE: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgvector:5432/${POSTGRES_DB}
    depends_on:
      pgvector:
        condition: service_healthy
    volumes:
      # Pfad links: HOST Server
      # Pfad rechts: Container Destination
      - /opt/portainer_data/secrets/gcloud-ragspert.json:/app/secrets/gcloud-ragspert.json:ro
    restart: unless-stopped
    shm_size: '2gb'
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy
      traefik.http.routers.ragspert-secure.entrypoints: websecure
      traefik.http.routers.ragspert-secure.rule: Host(`ragspert.de`)
      traefik.http.routers.ragspert-secure.tls: "true"
      traefik.http.routers.ragspert-secure.tls.certresolver: http_resolver
      traefik.http.routers.ragspert-secure.middlewares: default@file
      traefik.http.routers.ragspert-secure.service: ragspert
      traefik.http.routers.ragspert.entrypoints: web
      traefik.http.routers.ragspert.rule: Host(`ragspert.de`)
      traefik.http.services.ragspert.loadbalancer.server.port: "8080"
    networks:
      - internal
      - proxy

volumes:
  pgvector_data:
    driver: local

networks:
  internal:
    driver: bridge
    internal: true
  proxy:
    external: true
